#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

python3 - <<'PY'
from __future__ import annotations

import json
import re
from pathlib import Path
from datetime import datetime, timezone

TMP = Path("/tmp/safeops-demo")
REMEDIATION_OUTPUT = TMP / "latest_remediation_output.json"
INCIDENT_FILE = TMP / "latest_incident_id"
OUT_DIR = TMP / "prevention-pr"

if not REMEDIATION_OUTPUT.exists():
    raise SystemExit("ERROR: Missing /tmp/safeops-demo/latest_remediation_output.json. Run the full demo first.")

try:
    remediation = json.loads(REMEDIATION_OUTPUT.read_text(errors="replace"))
except Exception as exc:
    raise SystemExit(f"ERROR: Could not parse remediation output: {exc}")

incident_id = remediation.get("incident_id") or (INCIDENT_FILE.read_text().strip() if INCIDENT_FILE.exists() else "unknown")
service = remediation.get("execution", {}).get("service") or remediation.get("memory", {}).get("service") or "checkout-api"
namespace = remediation.get("execution", {}).get("namespace") or remediation.get("memory", {}).get("namespace") or "demo"
root_cause = remediation.get("memory", {}).get("root_cause") or "Required runtime configuration was missing."
confidence = remediation.get("memory", {}).get("confidence")
validated = remediation.get("policy_decision", {}).get("validated_parameters", {})
env_name = validated.get("env_name") or remediation.get("execution", {}).get("parameters", {}).get("env_name") or "REDIS_URL"
env_value = validated.get("env_value") or remediation.get("execution", {}).get("parameters", {}).get("env_value") or "redis://redis.demo.svc.cluster.local:6379"
verification = remediation.get("verification", {})
checks = verification.get("checks", [])
branch = f"safeops/prevent-{service}-{env_name.lower()}".replace("_", "-")
branch = re.sub(r"[^a-zA-Z0-9._/-]+", "-", branch)

OUT_DIR.mkdir(parents=True, exist_ok=True)
(OUT_DIR / ".safeops" / "prevention").mkdir(parents=True, exist_ok=True)
(OUT_DIR / "ci").mkdir(parents=True, exist_ok=True)
(OUT_DIR / ".github" / "workflows").mkdir(parents=True, exist_ok=True)

def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")

write(
    OUT_DIR / ".safeops" / "prevention" / f"{service}-required-env.yaml",
    f"""# Generated by SafeOps prevention simulation
# Incident: {incident_id}
# Purpose: prevent repeat deployments where {env_name} is missing for {service}.

apiVersion: safeops.dev/v1alpha1
kind: RequiredEnvironmentGuardrail
metadata:
  name: {service}-{env_name.lower().replace('_', '-')}
spec:
  service: {service}
  namespace: {namespace}
  deployment: {service}
  requiredEnv:
    - name: {env_name}
      expectedValueHint: {env_value}
  failureMode: fail_ci
  reason: >-
    Previous incident {incident_id} was caused by a missing or misconfigured
    {env_name}. SafeOps recommends blocking deployments when this variable is absent.
""",
)

write(
    OUT_DIR / "ci" / "check_required_env.py",
    f'''#!/usr/bin/env python3
"""Fail CI if Kubernetes manifests remove required environment variables.

Generated by SafeOps prevention simulation for incident {incident_id}.
This is intentionally small and reviewable. In a real repository, wire this into
GitHub Actions, GitLab CI, Jenkins, or your deployment pipeline.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except Exception:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

REQUIRED = {{"{env_name}"}}
DEPLOYMENT_NAME = "{service}"
SEARCH_DIRS = [Path("demo/k8s"), Path("k8s"), Path("manifests"), Path("deploy")]


def iter_yaml_files():
    for directory in SEARCH_DIRS:
        if directory.exists():
            yield from directory.rglob("*.yaml")
            yield from directory.rglob("*.yml")


def check_file(path: Path) -> list[str]:
    errors: list[str] = []
    try:
        docs = list(yaml.safe_load_all(path.read_text()))
    except Exception as exc:
        return [f"{{path}}: could not parse YAML: {{exc}}"]

    for doc in docs:
        if not isinstance(doc, dict):
            continue
        if doc.get("kind") != "Deployment":
            continue
        metadata = doc.get("metadata") or {{}}
        if metadata.get("name") != DEPLOYMENT_NAME:
            continue
        containers = (
            doc.get("spec", {{}})
            .get("template", {{}})
            .get("spec", {{}})
            .get("containers", [])
        )
        for container in containers:
            env_names = {{item.get("name") for item in container.get("env", []) if isinstance(item, dict)}}
            missing = sorted(REQUIRED - env_names)
            if missing:
                errors.append(f"{{path}}: deployment/{{DEPLOYMENT_NAME}} missing env vars: {{', '.join(missing)}}")
    return errors


def main() -> int:
    files = list(iter_yaml_files())
    if not files:
        print("No Kubernetes YAML files found to check.")
        return 0
    errors: list[str] = []
    for path in files:
        errors.extend(check_file(path))
    if errors:
        print("SafeOps prevention check failed:")
        for error in errors:
            print(f"- {{error}}")
        return 1
    print("SafeOps prevention check passed: required env vars are present.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
''',
)

write(
    OUT_DIR / ".github" / "workflows" / "safeops-required-env-check.yml",
    f"""name: SafeOps required env check

on:
  pull_request:
    paths:
      - 'demo/k8s/**'
      - 'k8s/**'
      - 'manifests/**'
      - 'deploy/**'
      - 'ci/check_required_env.py'

jobs:
  required-env-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyyaml
      - run: python ci/check_required_env.py
""",
)

checks_text = "\n".join(
    f"- {check.get('name', 'check')}: {check.get('status', 'unknown')} — {check.get('detail', '')}" for check in checks
) or "- Verification checks were not available."

write(
    OUT_DIR / "PR_TITLE.txt",
    f"SafeOps: prevent missing {env_name} for {service}\n",
)

write(
    OUT_DIR / "PR_BODY.md",
    f"""## SafeOps prevention PR draft

This PR draft was generated after SafeOps remediated incident `{incident_id}`.

### Incident summary

- Service: `{service}`
- Namespace: `{namespace}`
- Root cause: {root_cause}
- Confidence: {confidence if confidence is not None else 'unknown'}
- Remediation used: restore `{env_name}` on `deployment/{service}`

### Why this prevention is needed

SafeOps observed that the deployment became unhealthy when `{env_name}` was missing or misconfigured. The remediation succeeded, but the same failure can happen again unless the deployment pipeline blocks this class of mistake.

### Proposed guardrail

This PR adds a CI/CD prevention check that fails deployment-related pull requests when `deployment/{service}` does not include `{env_name}`.

### Files included in this draft

- `.safeops/prevention/{service}-required-env.yaml`
- `ci/check_required_env.py`
- `.github/workflows/safeops-required-env-check.yml`

### Verification from the remediated incident

{checks_text}

### SafeOps note

This is a simulated PR package. Milestone 12 should connect this workflow to GitHub/GitLab so AURA can open a real pull request after human approval.
""",
)

write(
    OUT_DIR / "README.md",
    f"""# SafeOps prevention PR simulation

Generated at: {datetime.now(timezone.utc).isoformat()}
Incident: `{incident_id}`
Suggested branch: `{branch}`

This directory contains a simulated prevention PR package. It does not modify your repository automatically.

## Review the generated files

```bash
find {OUT_DIR} -type f -maxdepth 5 -print
sed -n '1,200p' {OUT_DIR}/PR_BODY.md
```

## Future real PR flow

Milestone 12 should turn this into a real GitHub/GitLab PR:

1. Create branch `{branch}`
2. Add the generated prevention files
3. Commit the guardrail
4. Open PR with the generated body
5. Request engineer approval
""",
)

print("SafeOps prevention PR draft generated.")
print(f"Incident:           {incident_id}")
print(f"Service:            {service}")
print(f"Required env:       {env_name}")
print(f"Suggested branch:   {branch}")
print(f"Output directory:   {OUT_DIR}")
print()
print("Generated files:")
for path in sorted(OUT_DIR.rglob("*")):
    if path.is_file():
        print(f"- {path}")
PY
